name: Word Scramble CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: '0 14 * * *' # Midnight AEST

jobs:
  backend:
    name: Test Express API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests (save logs)
        run: npm test | tee jest.log

      - name: Upload backend test log
        uses: actions/upload-artifact@v4
        with:
          name: backend-jest-log
          path: server/jest.log

  frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests (save logs)
        run: npm run test -- --coverage | tee vitest.log

      - name: Upload frontend test log
        uses: actions/upload-artifact@v4
        with:
          name: frontend-vitest-log
          path: client/vitest.log

      - name: Build frontend
        run: npm run build
