name: Deploy Word Scramble App to AWS

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule: 
    - cron: '30 14 * * *' # 12:30am AEST

jobs:
  deploy:
    name: Build, Push to ECR, and Deploy to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-southeast-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set dynamic image tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "IMAGE_TAG=nightly" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=v3" >> $GITHUB_ENV
          fi
          echo "CLIENT_IMAGE=${{ secrets.ECR_CLIENT_REPO }}:$IMAGE_TAG" >> $GITHUB_ENV
          echo "API_IMAGE=${{ secrets.ECR_API_REPO }}:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_CLIENT_REPO }}
          aws ecr get-login-password --region $AWS_REGION | \
          docker login --username AWS --password-stdin ${{ secrets.ECR_API_REPO }}

      - name: Build and push client image
        run: |
          docker build -t $CLIENT_IMAGE ./client
          docker push $CLIENT_IMAGE

      - name: Build and push API image
        run: |
          docker build -t $API_IMAGE ./server
          docker push $API_IMAGE

      - name: Update ECS client service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_CLIENT_SERVICE_NAME }} \
            --force-new-deployment

      - name: Update ECS API service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER_NAME }} \
            --service ${{ secrets.ECS_API_SERVICE_NAME }} \
            --force-new-deployment
